requires = ["tox>=4.23.2"]
deps = ["tox-uv", "uv"]
env_list = ["test", "checks"]
no_package = true

[env_run_base]
#runner = "uv-venv-lock-runner"
runner = "uv-venv-runner"
# commands = [["uv", "sync"]]
setenv = {PYTHONPATH = ".", PYTHONHASHSEED = "0"}

[env.test]
description = "Run tests under {base_python}"
with_dev = true
dependency_groups = ["testing"]
commands = [
	["uv", "run", "pytest", "-s", "-vv"]
]

[env.checks]
description = "Run checks under {base_python}"
with_dev = "{[test]with_dev}"
dependency_groups = ["typing"]
ignore_errors = true
commands = [
	["flake8", "_model", "tests"],
	["black", "--check", "--diff", "."],
	["isort", "--check", "--diff", "."],
	["mypy", "_model", "tests"]
]

[env.train]
description = "Train the model"
commands = [["uv", "run", "_model/train_pipeline.py"]]