# Package Overview
package_name: _model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict
target: Cover_Type

pipeline_name: _model
pipeline_save_file: _model_output_v

# Will cause syntax errors
variables_to_rename:
  badvarName: newName

features:
  - Elevation
  - Horizontal_Distance_To_Fire_Points
  - Horizontal_Distance_To_Roadways
  - Soil_Type
  - Horizontal_Distance_To_Hydrology
  - Vertical_Distance_To_Hydrology
  - Wilderness_Area
  - Aspect
  - Hillshade_Noon
  - Slope

# set train/test split
test_size: 0.2

# seed
random_state: 711

# Hyperparameters
n_estimators: 50
min_samples_split: 5
min_samples_leaf: 2 
max_samples: 0.75
max_leaf_nodes: 10000 
max_features: 0.8
max_depth: 100

# Other necessary feature remappings/engineerings
categorical_vars:
  - Wilderness_Area
  - Soil_Type

trig_transform:
  - Slope
  - Aspect

transformed_features_drop:
  - SinSlope